### ISSUE TITLE
Invalid URL of image?

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/solid-crs#309]
If I add a URL of an image to field 'Bestand' an error message sometimes appears. But I don't see what's wrong with the URL (e.g. `https://www.vidyard.com/media/University-of-Waterloo.png`).

![invalid_url_for_image](https://user-images.githubusercontent.com/606948/122075729-962d4780-cdfa-11eb-853b-e26005fb32af.png)

**Comment by lem-onade** [comment]
Seems to be CORS related for https://www.vidyard.com/media/University-of-Waterloo.png. The server did not set the required headers for the resource to be fetched across origins. Happens when we're trying to check the resource's content type (jpg, png, ...) like we discussed when deciding the form fields. I'll look into it, but it might be best to just omit this content type check, as the URL you used works fine when put in an `<img>` tag.

We were also still planning on supporting an image upload for object images, which I suppose would be used more frequently than the URL input field.

**Comment by sdevalk** [comment]
Ah, I see! Yes, I agree: perhaps it's better to omit this check - it's then up to the user to provide a URL that points to a valid image.
